---
Metrics/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingBlankLines:
  EnforcedStyle: final_blank_line
  SupportedStyles:
    - final_newline
    - final_blank_line

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/NonNilCheck:
  IncludeSemanticChanges: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 8

Style/AccessModifierIndentation:
  EnforcedStyle: outdent
  SupportedStyles:
    - outdent

Style/RaiseArgs:
  EnforcedStyle: exploded
  SupportedStyles:
    - compact
    - exploded

Metrics/AbcSize:
  Max: 20

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '()'
    '%i': '[]'
    '%s': '()'
    '%q': '()'
    '%Q': '()'
    '%w': '[]'
    '%W': '[]'
    '%r': '{}'
    '%x': '()'

